package comphouse

// partially autogenerated using https://mholt.github.io/json-to-go/

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companyprofile
type CompanyProfile struct {
	Accounts struct {
		AccountingReferenceDate struct {
			Day   int `json:"day,string"`
			Month int `json:"month,string"`
		} `json:"accounting_reference_date"`
		LastAccounts struct {
			MadeUpTo string      `json:"made_up_to"`
			Type     interface{} `json:"type"`
		} `json:"last_accounts"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      bool   `json:"overdue"`
	} `json:"accounts"`
	AnnualReturn struct {
		LastMadeUpTo string `json:"last_made_up_to"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      bool   `json:"overdue"`
	} `json:"annual_return"`
	BranchCompanyDetails struct {
		BusinessActivity    string `json:"business_activity"`
		ParentCompanyName   string `json:"parent_company_name"`
		ParentCompanyNumber string `json:"parent_company_number"`
	} `json:"branch_company_details"`
	CanFile               bool   `json:"can_file"`
	CompanyName           string `json:"company_name"`
	CompanyNumber         string `json:"company_number"`
	CompanyStatus         string `json:"company_status"`
	CompanyStatusDetail   string `json:"company_status_detail"`
	ConfirmationStatement struct {
		LastMadeUpTo string `json:"last_made_up_to"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      bool   `json:"overdue"`
	} `json:"confirmation_statement"`
	DateOfCessation       string `json:"date_of_cessation"`
	DateOfCreation        string `json:"date_of_creation"`
	Etag                  string `json:"etag"`
	ForeignCompanyDetails struct {
		AccountingRequirement struct {
			ForeignAccountType        string `json:"foreign_account_type"`
			TermsOfAccountPublication string `json:"terms_of_account_publication"`
		} `json:"accounting_requirement"`
		Accounts struct {
			AccountPeriodFrom struct {
				Day   int `json:"day"`
				Month int `json:"month"`
			} `json:"account_period_from:"`
			AccountPeriodTo struct {
				Day   int `json:"day"`
				Month int `json:"month"`
			} `json:"account_period_to"`
			MustFileWithin struct {
				Months int `json:"months"`
			} `json:"must_file_within"`
		} `json:"accounts"`
		BusinessActivity            string `json:"business_activity"`
		CompanyType                 string `json:"company_type"`
		GovernedBy                  string `json:"governed_by"`
		IsACreditFinanceInstitution bool   `json:"is_a_credit_finance_institution"`
		OriginatingRegistry         struct {
			Country string `json:"country"`
			Name    string `json:"name"`
		} `json:"originating_registry"`
		RegistrationNumber string `json:"registration_number"`
	} `json:"foreign_company_details"`
	HasBeenLiquidated          bool   `json:"has_been_liquidated"`
	HasCharges                 bool   `json:"has_charges"`
	HasInsolvencyHistory       bool   `json:"has_insolvency_history"`
	IsCommunityInterestCompany bool   `json:"is_community_interest_company"`
	Jurisdiction               string `json:"jurisdiction"`
	LastFullMembersListDate    string `json:"last_full_members_list_date"`
	Links                      struct {
		PersonsWithSignificantControl           string `json:"persons_with_significant_control"`
		PersonsWithSignificantControlStatements string `json:"persons_with_significant_control_statements"`
		Registers                               string `json:"registers"`
		Self                                    string `json:"self"`
	} `json:"links"`
	PreviousCompanyNames []struct {
		CeasedOn      string `json:"ceased_on"`
		EffectiveFrom string `json:"effective_from"`
		Name          string `json:"name"`
	} `json:"previous_company_names"`
	RegisteredOfficeAddress struct {
		AddressLine1 string `json:"address_line_1"`
		AddressLine2 string `json:"address_line_2"`
		CareOf       string `json:"care_of"`
		Country      string `json:"country"`
		Locality     string `json:"locality"`
		PoBox        string `json:"po_box"`
		PostalCode   string `json:"postal_code"`
		Premises     string `json:"premises"`
		Region       string `json:"region"`
	} `json:"registered_office_address"`
	RegisteredOfficeIsInDispute          bool   `json:"registered_office_is_in_dispute"`
	SicCodes                             []SIC  `json:"sic_codes"`
	Type                                 string `json:"type"`
	UndeliverableRegisteredOfficeAddress bool   `json:"undeliverable_registered_office_address"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/registeredofficeaddress
type RegisteredOfficeAddress struct {
	AddressLine1 string `json:"address_line_1"`
	AddressLine2 string `json:"address_line_2"`
	Country      string `json:"country"`
	Etag         string `json:"etag"`
	Kind         string `json:"kind"`
	Links        struct {
		Self string `json:"self"`
	} `json:"links"`
	Locality   string `json:"locality"`
	PoBox      string `json:"po_box"`
	PostalCode string `json:"postal_code"`
	Premises   string `json:"premises"`
	Region     string `json:"region"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/officerlist
type OfficerList struct {
	ActiveCount int    `json:"active_count"`
	Etag        string `json:"etag"`
	Items       []struct {
		Address struct {
			AddressLine1 string `json:"address_line_1"`
			AddressLine2 string `json:"address_line_2"`
			CareOf       string `json:"care_of"`
			Country      string `json:"country"`
			Locality     string `json:"locality"`
			PoBox        string `json:"po_box"`
			PostalCode   string `json:"postal_code"`
			Premises     string `json:"premises"`
			Region       string `json:"region"`
		} `json:"address"`
		AppointedOn        string `json:"appointed_on"`
		CountryOfResidence string `json:"country_of_residence"`
		DateOfBirth        struct {
			Day   int `json:"day"`
			Month int `json:"month"`
			Year  int `json:"year"`
		} `json:"date_of_birth"`
		FormerNames []struct {
			Forenames string `json:"forenames"`
			Surname   string `json:"surname"`
		} `json:"former_names"`
		Identification struct {
			IdentificationType string `json:"identification_type"`
			LegalAuthority     string `json:"legal_authority"`
			LegalForm          string `json:"legal_form"`
			PlaceRegistered    string `json:"place_registered"`
			RegistrationNumber string `json:"registration_number"`
		} `json:"identification"`
		Links struct {
			Officer struct {
				Appointments string `json:"appointments"`
			} `json:"officer"`
			Self string `json:"self"`
		} `json:"links"`
		Name        string `json:"name"`
		Nationality string `json:"nationality"`
		Occupation  string `json:"occupation"`
		OfficerRole string `json:"officer_role"`
		ResignedOn  string `json:"resigned_on"`
	} `json:"items"`
	ItemsPerPage int    `json:"items_per_page"`
	Kind         string `json:"kind"`
	Links        struct {
		Self string `json:"self"`
	} `json:"links"`
	ResignedCount int `json:"resigned_count"`
	StartIndex    int `json:"start_index"`
	TotalResults  int `json:"total_results"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/officersummary
type OfficerSummary struct {
	Address struct {
		AddressLine1 string `json:"address_line_1"`
		AddressLine2 string `json:"address_line_2"`
		CareOf       string `json:"care_of"`
		Country      string `json:"country"`
		Locality     string `json:"locality"`
		PoBox        string `json:"po_box"`
		PostalCode   string `json:"postal_code"`
		Premises     string `json:"premises"`
		Region       string `json:"region"`
	} `json:"address"`
	AppointedOn        string `json:"appointed_on"`
	CountryOfResidence string `json:"country_of_residence"`
	DateOfBirth        struct {
		Day   int `json:"day"`
		Month int `json:"month"`
		Year  int `json:"year"`
	} `json:"date_of_birth"`
	FormerNames []struct {
		Forenames string `json:"forenames"`
		Surname   string `json:"surname"`
	} `json:"former_names"`
	Identification struct {
		IdentificationType string `json:"identification_type"`
		LegalAuthority     string `json:"legal_authority"`
		LegalForm          string `json:"legal_form"`
		PlaceRegistered    string `json:"place_registered"`
		RegistrationNumber string `json:"registration_number"`
	} `json:"identification"`
	Links struct {
		Officer struct {
			Appointments string `json:"appointments"`
		} `json:"officer"`
		Self string `json:"self"`
	} `json:"links"`
	Name        string `json:"name"`
	Nationality string `json:"nationality"`
	Occupation  string `json:"occupation"`
	OfficerRole string `json:"officer_role"`
	ResignedOn  string `json:"resigned_on"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companyregister
type CompanyRegister struct {
	CompanyNumber string `json:"company_number"`
	Etag          string `json:"etag"`
	Kind          string `json:"kind"`
	Links         struct {
		Self string `json:"self"`
	} `json:"links"`
	Registers struct {
		Directors struct {
			Items []struct {
				Links struct {
					Filing string `json:"filing"`
				} `json:"links"`
				MovedOn         string `json:"moved_on"`
				RegisterMovedTo string `json:"register_moved_to"`
			} `json:"items"`
			Links struct {
				DirectorsRegister string `json:"directors_register"`
			} `json:"links"`
			RegisterType string `json:"register_type"`
		} `json:"directors"`
		LlpMembers struct {
			Items []struct {
				Links struct {
					Filing string `json:"filing"`
				} `json:"links"`
				MovedOn         string `json:"moved_on"`
				RegisterMovedTo string `json:"register_moved_to"`
			} `json:"items"`
			Links struct {
				LlpMembers string `json:"llp_members"`
			} `json:"links"`
			RegisterType string `json:"register_type"`
		} `json:"llp_members"`
		LlpUsualResidentialAddress struct {
			Items []struct {
				Links struct {
					Filing string `json:"filing"`
				} `json:"links"`
				MovedOn         string `json:"moved_on"`
				RegisterMovedTo string `json:"register_moved_to"`
			} `json:"items"`
			Links struct {
				LlpUsualResidentialAddress string `json:"llp_usual_residential_address"`
			} `json:"links"`
			RegisterType string `json:"register_type"`
		} `json:"llp_usual_residential_address"`
		Members struct {
			Items []struct {
				Links struct {
					Filing string `json:"filing"`
				} `json:"links"`
				MovedOn         string `json:"moved_on"`
				RegisterMovedTo string `json:"register_moved_to"`
			} `json:"items"`
			Links struct {
				Members string `json:"members"`
			} `json:"links"`
			RegisterType string `json:"register_type"`
		} `json:"members"`
		PersonsWithSignificantControl struct {
			Items []struct {
				Links struct {
					Filing string `json:"filing"`
				} `json:"links"`
				MovedOn         string `json:"moved_on"`
				RegisterMovedTo string `json:"register_moved_to"`
			} `json:"items"`
			Links struct {
				PersonsWithSignificantControlRegister string `json:"persons_with_significant_control_register"`
			} `json:"links"`
			RegisterType string `json:"register_type"`
		} `json:"persons_with_significant_control"`
		Secretaries struct {
			Items []struct {
				Links struct {
					Filing string `json:"filing"`
				} `json:"links"`
				MovedOn         string `json:"moved_on"`
				RegisterMovedTo string `json:"register_moved_to"`
			} `json:"items"`
			Links struct {
				SecretariesRegister string `json:"secretaries_register"`
			} `json:"links"`
			RegisterType string `json:"register_type"`
		} `json:"secretaries"`
		UsualResidentialAddress struct {
			Items []struct {
				Links struct {
					Filing string `json:"filing"`
				} `json:"links"`
				MovedOn         string `json:"moved_on"`
				RegisterMovedTo string `json:"register_moved_to"`
			} `json:"items"`
			Links struct {
				UsualResidentialAddress string `json:"usual_residential_address"`
			} `json:"links"`
			RegisterType string `json:"register_type"`
		} `json:"usual_residential_address"`
	} `json:"registers"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/chargelist
type ChargeList struct {
	Etag  string `json:"etag"`
	Items []struct {
		AcquiredOn            string `json:"acquired_on"`
		AssestsCeasedReleased string `json:"assests_ceased_released"`
		ChargeCode            string `json:"charge_code"`
		ChargeNumber          int    `json:"charge_number"`
		Classification        struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"classification"`
		CoveringInstrumentDate string `json:"covering_instrument_date"`
		CreatedOn              string `json:"created_on"`
		DeliveredOn            string `json:"delivered_on"`
		Etag                   string `json:"etag"`
		ID                     string `json:"id"`
		InsolvencyCases        []struct {
			CaseNumber int `json:"case_number"`
			Links      []struct {
				Case string `json:"case"`
			} `json:"links"`
			TransactionID int `json:"transaction_id"`
		} `json:"insolvency_cases"`
		Links struct {
			Self string `json:"self"`
		} `json:"links"`
		MoreThanFourPersonsEntitled bool `json:"more_than_four_persons_entitled"`
		Particulars                 struct {
			ChargorActingAsBareTrustee bool   `json:"chargor_acting_as_bare_trustee"`
			ContainsFixedCharge        bool   `json:"contains_fixed_charge"`
			ContainsFloatingCharge     bool   `json:"contains_floating_charge"`
			ContainsNegativePledge     bool   `json:"contains_negative_pledge"`
			Description                string `json:"description"`
			FloatingChargeCoversAll    bool   `json:"floating_charge_covers_all"`
			Type                       string `json:"type"`
		} `json:"particulars"`
		PersonsEntitled []struct {
			Name string `json:"name"`
		} `json:"persons_entitled"`
		ResolvedOn          string `json:"resolved_on"`
		SatisfiedOn         string `json:"satisfied_on"`
		ScottishAlterations []struct {
			Description                  string `json:"description"`
			HasAlterationsToOrder        bool   `json:"has_alterations_to_order"`
			HasAlterationsToProhibitions bool   `json:"has_alterations_to_prohibitions"`
			HasAlterationsToProvisions   bool   `json:"has_alterations_to_provisions"`
			Type                         string `json:"type"`
		} `json:"scottish_alterations"`
		SecuredDetails struct {
			Description string `json:"description"`
			Type        string `json:"type"`
		} `json:"secured_details"`
		Status       string `json:"status"`
		Transactions []struct {
			DeliveredOn          string `json:"delivered_on"`
			FilingType           string `json:"filing_type"`
			InsolvencyCaseNumber int    `json:"insolvency_case_number"`
			Links                struct {
				Filing         string `json:"filing"`
				InsolvencyCase string `json:"insolvency_case"`
			} `json:"links"`
			TransactionID int `json:"transaction_id"`
		} `json:"transactions"`
	} `json:"items"`
	PartSatisfiedCount int `json:"part_satisfied_count"`
	SatisfiedCount     int `json:"satisfied_count"`
	TotalCount         int `json:"total_count"`
	UnfilteredCount    int `json:"unfiltered_count"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/chargedetails
type ChargeDetails struct {
	AcquiredOn            string `json:"acquired_on"`
	AssestsCeasedReleased string `json:"assests_ceased_released"`
	ChargeCode            string `json:"charge_code"`
	ChargeNumber          int    `json:"charge_number"`
	Classification        struct {
		Description string `json:"description"`
		Type        string `json:"type"`
	} `json:"classification"`
	CoveringInstrumentDate string `json:"covering_instrument_date"`
	CreatedOn              string `json:"created_on"`
	DeliveredOn            string `json:"delivered_on"`
	Etag                   string `json:"etag"`
	ID                     string `json:"id"`
	InsolvencyCases        []struct {
		CaseNumber int `json:"case_number"`
		Links      []struct {
			Case string `json:"case"`
		} `json:"links"`
		TransactionID int `json:"transaction_id"`
	} `json:"insolvency_cases"`
	Links struct {
		Self string `json:"self"`
	} `json:"links"`
	MoreThanFourPersonsEntitled bool `json:"more_than_four_persons_entitled"`
	Particulars                 struct {
		ChargorActingAsBareTrustee bool   `json:"chargor_acting_as_bare_trustee"`
		ContainsFixedCharge        bool   `json:"contains_fixed_charge"`
		ContainsFloatingCharge     bool   `json:"contains_floating_charge"`
		ContainsNegativePledge     bool   `json:"contains_negative_pledge"`
		Description                string `json:"description"`
		FloatingChargeCoversAll    bool   `json:"floating_charge_covers_all"`
		Type                       string `json:"type"`
	} `json:"particulars"`
	PersonsEntitled []struct {
		Name string `json:"name"`
	} `json:"persons_entitled"`
	ResolvedOn          string `json:"resolved_on"`
	SatisfiedOn         string `json:"satisfied_on"`
	ScottishAlterations []struct {
		Description                  string `json:"description"`
		HasAlterationsToOrder        bool   `json:"has_alterations_to_order"`
		HasAlterationsToProhibitions bool   `json:"has_alterations_to_prohibitions"`
		HasAlterationsToProvisions   bool   `json:"has_alterations_to_provisions"`
		Type                         string `json:"type"`
	} `json:"scottish_alterations"`
	SecuredDetails []struct {
		Description string `json:"description"`
		Type        string `json:"type"`
	} `json:"secured_details"`
	Status       string `json:"status"`
	Transactions []struct {
		DeliveredOn          string `json:"delivered_on"`
		FilingType           string `json:"filing_type"`
		InsolvencyCaseNumber int    `json:"insolvency_case_number"`
		Links                struct {
			Filing         string `json:"filing"`
			InsolvencyCase string `json:"insolvency_case"`
		} `json:"links"`
		TransactionID int `json:"transaction_id"`
	} `json:"transactions"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/search
type Search struct {
	Etag  string `json:"etag"`
	Items []struct {
		Address struct {
			AddressLine1 string `json:"address_line_1"`
			AddressLine2 string `json:"address_line_2"`
			CareOf       string `json:"care_of"`
			Country      string `json:"country"`
			Locality     string `json:"locality"`
			PoBox        string `json:"po_box"`
			PostalCode   string `json:"postal_code"`
			Region       string `json:"region"`
		} `json:"address"`
		AddressSnippet        string   `json:"address_snippet"`
		Description           string   `json:"description"`
		DescriptionIdentifier []string `json:"description_identifier"`
		Kind                  string   `json:"kind"`
		Links                 struct {
			Self string `json:"self"`
		} `json:"links"`
		Matches struct {
			AddressSnippet []int `json:"address_snippet"`
			Snippet        []int `json:"snippet"`
			Title          []int `json:"title"`
		} `json:"matches"`
		Snippet string `json:"snippet"`
		Title   string `json:"title"`
	} `json:"items"`
	ItemsPerPage int    `json:"items_per_page"`
	Kind         string `json:"kind"`
	StartIndex   int    `json:"start_index"`
	TotalResults int    `json:"total_results"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companysearch
type CompanySearch struct {
	Etag  string `json:"etag"`
	Items []struct {
		Address struct {
			AddressLine1 string `json:"address_line_1"`
			AddressLine2 string `json:"address_line_2"`
			CareOf       string `json:"care_of"`
			Country      string `json:"country"`
			Locality     string `json:"locality"`
			PoBox        string `json:"po_box"`
			PostalCode   string `json:"postal_code"`
			Region       string `json:"region"`
		} `json:"address"`
		AddressSnippet        string   `json:"address_snippet"`
		CompanyNumber         string   `json:"company_number"`
		CompanyStatus         string   `json:"company_status"`
		CompanyType           string   `json:"company_type"`
		DateOfCessation       string   `json:"date_of_cessation"`
		DateOfCreation        string   `json:"date_of_creation"`
		Description           string   `json:"description"`
		DescriptionIdentifier []string `json:"description_identifier"`
		Kind                  string   `json:"kind"`
		Links                 struct {
			Self string `json:"self"`
		} `json:"links"`
		Matches struct {
			AddressSnippet []int `json:"address_snippet"`
			Snippet        []int `json:"snippet"`
			Title          []int `json:"title"`
		} `json:"matches"`
		Snippet string `json:"snippet"`
		Title   string `json:"title"`
	} `json:"items"`
	ItemsPerPage int    `json:"items_per_page"`
	Kind         string `json:"kind"`
	StartIndex   int    `json:"start_index"`
	TotalResults int    `json:"total_results"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/officersearch
type OfficerSearch struct {
	Etag  string `json:"etag"`
	Items []struct {
		Address struct {
			AddressLine1 string `json:"address_line_1"`
			AddressLine2 string `json:"address_line_2"`
			CareOf       string `json:"care_of"`
			Country      string `json:"country"`
			Locality     string `json:"locality"`
			PoBox        string `json:"po_box"`
			PostalCode   string `json:"postal_code"`
			Premises     string `json:"premises"`
			Region       string `json:"region"`
		} `json:"address"`
		AddressSnippet   string `json:"address_snippet"`
		AppointmentCount int    `json:"appointment_count"`
		DateOfBirth      struct {
			Month int `json:"month"`
			Year  int `json:"year"`
		} `json:"date_of_birth"`
		Description            string   `json:"description"`
		DescriptionIdentifiers []string `json:"description_identifiers"`
		Kind                   string   `json:"kind"`
		Links                  struct {
			Self string `json:"self"`
		} `json:"links"`
		Matches struct {
			AddressSnippet []int `json:"address_snippet"`
			Snippet        []int `json:"snippet"`
			Title          []int `json:"title"`
		} `json:"matches"`
		Snippet string `json:"snippet"`
		Title   string `json:"title"`
	} `json:"items"`
	ItemsPerPage int    `json:"items_per_page"`
	Kind         string `json:"kind"`
	StartIndex   int    `json:"start_index"`
	TotalResults int    `json:"total_results"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/disqualifiedofficersearch
type DisqualifiedOfficerSearch struct {
	Etag  string `json:"etag"`
	Items []struct {
		Address struct {
			AddressLine1 string `json:"address_line_1"`
			AddressLine2 string `json:"address_line_2"`
			Country      string `json:"country"`
			Locality     string `json:"locality"`
			PostalCode   string `json:"postal_code"`
			Premises     string `json:"premises"`
			Region       string `json:"region"`
		} `json:"address"`
		AddressSnippet         string   `json:"address_snippet"`
		DateOfBirth            string   `json:"date_of_birth"`
		Description            string   `json:"description"`
		DescriptionIdentifiers []string `json:"description_identifiers"`
		Kind                   string   `json:"kind"`
		Links                  struct {
			Self string `json:"self"`
		} `json:"links"`
		Matches struct {
			AddressSnippet []int `json:"address_snippet"`
			Snippet        []int `json:"snippet"`
			Title          []int `json:"title"`
		} `json:"matches"`
		Snippet string `json:"snippet"`
		Title   string `json:"title"`
	} `json:"items"`
	ItemsPerPage int    `json:"items_per_page"`
	Kind         string `json:"kind"`
	StartIndex   int    `json:"start_index"`
	TotalResults int    `json:"total_results"`
}
