package comphouse

// autogenerated using https://mholt.github.io/json-to-go/

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companyprofile?v=latest
type CompanyProfile struct {
	Accounts struct {
		AccountingReferenceDate struct {
			Day   int `json:"day,string"`
			Month int `json:"month,string"`
		} `json:"accounting_reference_date"`
		LastAccounts struct {
			MadeUpTo string      `json:"made_up_to"`
			Type     interface{} `json:"type"`
		} `json:"last_accounts"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      bool   `json:"overdue"`
	} `json:"accounts"`
	AnnualReturn struct {
		LastMadeUpTo string `json:"last_made_up_to"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      bool   `json:"overdue"`
	} `json:"annual_return"`
	BranchCompanyDetails struct {
		BusinessActivity    string `json:"business_activity"`
		ParentCompanyName   string `json:"parent_company_name"`
		ParentCompanyNumber string `json:"parent_company_number"`
	} `json:"branch_company_details"`
	CanFile               bool   `json:"can_file"`
	CompanyName           string `json:"company_name"`
	CompanyNumber         string `json:"company_number"`
	CompanyStatus         string `json:"company_status"`
	CompanyStatusDetail   string `json:"company_status_detail"`
	ConfirmationStatement struct {
		LastMadeUpTo string `json:"last_made_up_to"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      bool   `json:"overdue"`
	} `json:"confirmation_statement"`
	DateOfCessation       string `json:"date_of_cessation"`
	DateOfCreation        string `json:"date_of_creation"`
	Etag                  string `json:"etag"`
	ForeignCompanyDetails struct {
		AccountingRequirement struct {
			ForeignAccountType        string `json:"foreign_account_type"`
			TermsOfAccountPublication string `json:"terms_of_account_publication"`
		} `json:"accounting_requirement"`
		Accounts struct {
			AccountPeriodFrom struct {
				Day   int `json:"day"`
				Month int `json:"month"`
			} `json:"account_period_from:"`
			AccountPeriodTo struct {
				Day   int `json:"day"`
				Month int `json:"month"`
			} `json:"account_period_to"`
			MustFileWithin struct {
				Months int `json:"months"`
			} `json:"must_file_within"`
		} `json:"accounts"`
		BusinessActivity            string `json:"business_activity"`
		CompanyType                 string `json:"company_type"`
		GovernedBy                  string `json:"governed_by"`
		IsACreditFinanceInstitution bool   `json:"is_a_credit_finance_institution"`
		OriginatingRegistry         struct {
			Country string `json:"country"`
			Name    string `json:"name"`
		} `json:"originating_registry"`
		RegistrationNumber string `json:"registration_number"`
	} `json:"foreign_company_details"`
	HasBeenLiquidated          bool   `json:"has_been_liquidated"`
	HasCharges                 bool   `json:"has_charges"`
	HasInsolvencyHistory       bool   `json:"has_insolvency_history"`
	IsCommunityInterestCompany bool   `json:"is_community_interest_company"`
	Jurisdiction               string `json:"jurisdiction"`
	LastFullMembersListDate    string `json:"last_full_members_list_date"`
	Links                      struct {
		PersonsWithSignificantControl           string `json:"persons_with_significant_control"`
		PersonsWithSignificantControlStatements string `json:"persons_with_significant_control_statements"`
		Registers                               string `json:"registers"`
		Self                                    string `json:"self"`
	} `json:"links"`
	PreviousCompanyNames []struct {
		CeasedOn      string `json:"ceased_on"`
		EffectiveFrom string `json:"effective_from"`
		Name          string `json:"name"`
	} `json:"previous_company_names"`
	RegisteredOfficeAddress struct {
		AddressLine1 string `json:"address_line_1"`
		AddressLine2 string `json:"address_line_2"`
		CareOf       string `json:"care_of"`
		Country      string `json:"country"`
		Locality     string `json:"locality"`
		PoBox        string `json:"po_box"`
		PostalCode   string `json:"postal_code"`
		Premises     string `json:"premises"`
		Region       string `json:"region"`
	} `json:"registered_office_address"`
	RegisteredOfficeIsInDispute          bool     `json:"registered_office_is_in_dispute"`
	SicCodes                             []string `json:"sic_codes"`
	Type                                 string   `json:"type"`
	UndeliverableRegisteredOfficeAddress bool     `json:"undeliverable_registered_office_address"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/registeredofficeaddress?v=latest
type RegisteredOfficeAddress struct {
	AddressLine1 string `json:"address_line_1"`
	AddressLine2 string `json:"address_line_2"`
	Country      string `json:"country"`
	Etag         string `json:"etag"`
	Kind         string `json:"kind"`
	Links        struct {
		Self string `json:"self"`
	} `json:"links"`
	Locality   string `json:"locality"`
	PoBox      string `json:"po_box"`
	PostalCode string `json:"postal_code"`
	Premises   string `json:"premises"`
	Region     string `json:"region"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/officerlist?v=latest
type OfficerList struct {
	// TODO
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/officersummary?v=latest
type OfficerSummary struct {
	// TODO
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companyregister?v=latest
type CompanyRegister struct {
	// TODO
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/chargelist?v=latest
type ChargeList struct {
	// TODO
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/chargedetails?v=latest
type ChargeDetails struct {
	// TODO
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/search?v=latest
type Search struct {
	Etag  string `json:"etag"`
	Items []struct {
		Address struct {
			AddressLine1 string `json:"address_line_1"`
			AddressLine2 string `json:"address_line_2"`
			CareOf       string `json:"care_of"`
			Country      string `json:"country"`
			Locality     string `json:"locality"`
			PoBox        string `json:"po_box"`
			PostalCode   string `json:"postal_code"`
			Region       string `json:"region"`
		} `json:"address"`
		AddressSnippet        string   `json:"address_snippet"`
		Description           string   `json:"description"`
		DescriptionIdentifier []string `json:"description_identifier"`
		Kind                  string   `json:"kind"`
		Links                 struct {
			Self string `json:"self"`
		} `json:"links"`
		Matches struct {
			AddressSnippet []int `json:"address_snippet"`
			Snippet        []int `json:"snippet"`
			Title          []int `json:"title"`
		} `json:"matches"`
		Snippet string `json:"snippet"`
		Title   string `json:"title"`
	} `json:"items"`
	ItemsPerPage int    `json:"items_per_page"`
	Kind         string `json:"kind"`
	StartIndex   int    `json:"start_index"`
	TotalResults int    `json:"total_results"`
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companysearch?v=latest
type CompanySearch struct {
	// TODO
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/officersearch?v=latest
type OfficerSearch struct {
	// TODO
}

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/disqualifiedofficersearch?v=latest
type DisqualifiedOfficerSearch struct {
	// TODO
}
