package comphouse

// autogenerated using https://mholt.github.io/json-to-go/

// https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources/companyprofile?v=latest
// fields have had their `Company` prefix removed, eg CompanyName -> Name
type CompanyProfile struct {
	Accounts struct {
		AccountingReferenceDate struct {
			Day   string `json:"day"`
			Month string `json:"month"`
		} `json:"accounting_reference_date"`
		LastAccounts struct {
			MadeUpTo string `json:"made_up_to"`
			Type     struct {
			} `json:"type"`
		} `json:"last_accounts"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      string `json:"overdue"`
	} `json:"accounts"`
	AnnualReturn struct {
		LastMadeUpTo string `json:"last_made_up_to"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      string `json:"overdue"`
	} `json:"annual_return"`
	BranchCompanyDetails struct {
		BusinessActivity    string `json:"business_activity"`
		ParentCompanyName   string `json:"parent_company_name"`
		ParentCompanyNumber string `json:"parent_company_number"`
	} `json:"branch_company_details"`
	CanFile               string `json:"can_file"`
	Name                  string `json:"company_name"`
	Number                string `json:"company_number"`
	Status                string `json:"company_status"`
	StatusDetail          string `json:"company_status_detail"`
	ConfirmationStatement struct {
		LastMadeUpTo string `json:"last_made_up_to"`
		NextDue      string `json:"next_due"`
		NextMadeUpTo string `json:"next_made_up_to"`
		Overdue      string `json:"overdue"`
	} `json:"confirmation_statement"`
	DateOfCessation       string `json:"date_of_cessation"`
	DateOfCreation        string `json:"date_of_creation"`
	Etag                  string `json:"etag"`
	ForeignCompanyDetails struct {
		AccountingRequirement struct {
			ForeignAccountType        string `json:"foreign_account_type"`
			TermsOfAccountPublication string `json:"terms_of_account_publication"`
		} `json:"accounting_requirement"`
		Accounts struct {
			AccountPeriodFrom struct {
				Day   string `json:"day"`
				Month string `json:"month"`
			} `json:"account_period_from:"`
			AccountPeriodTo struct {
				Day   string `json:"day"`
				Month string `json:"month"`
			} `json:"account_period_to"`
			MustFileWithin struct {
				Months string `json:"months"`
			} `json:"must_file_within"`
		} `json:"accounts"`
		BusinessActivity            string `json:"business_activity"`
		CompanyType                 string `json:"company_type"`
		GovernedBy                  string `json:"governed_by"`
		IsACreditFinanceInstitution string `json:"is_a_credit_finance_institution"`
		OriginatingRegistry         struct {
			Country string `json:"country"`
			Name    string `json:"name"`
		} `json:"originating_registry"`
		RegistrationNumber string `json:"registration_number"`
	} `json:"foreign_company_details"`
	HasBeenLiquidated          string `json:"has_been_liquidated"`
	HasCharges                 string `json:"has_charges"`
	HasInsolvencyHistory       string `json:"has_insolvency_history"`
	IsCommunityInterestCompany string `json:"is_community_interest_company"`
	Jurisdiction               string `json:"jurisdiction"`
	LastFullMembersListDate    string `json:"last_full_members_list_date"`
	Links                      struct {
		PersonsWithSignificantControl           string `json:"persons_with_significant_control"`
		PersonsWithSignificantControlStatements string `json:"persons_with_significant_control_statements"`
		Registers                               string `json:"registers"`
		Self                                    string `json:"self"`
	} `json:"links"`
	PreviousCompanyNames []struct {
		CeasedOn      string `json:"ceased_on"`
		EffectiveFrom string `json:"effective_from"`
		Name          string `json:"name"`
	} `json:"previous_company_names"`
	RegisteredOfficeAddress struct {
		AddressLine1 string `json:"address_line_1"`
		AddressLine2 string `json:"address_line_2"`
		CareOf       string `json:"care_of"`
		Country      string `json:"country"`
		Locality     string `json:"locality"`
		PoBox        string `json:"po_box"`
		PostalCode   string `json:"postal_code"`
		Premises     string `json:"premises"`
		Region       string `json:"region"`
	} `json:"registered_office_address"`
	RegisteredOfficeIsInDispute          string   `json:"registered_office_is_in_dispute"`
	SicCodes                             []string `json:"sic_codes"`
	Type                                 string   `json:"type"`
	UndeliverableRegisteredOfficeAddress string   `json:"undeliverable_registered_office_address"`
}
